spring.application.name=Room Reservation System

spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=sivlad2123326si

spring.jpa.hibernate.ddl-auto=update

spring.security.enabled=false
management.security.enabled=false
logging.level.org.springframework.security=DEBUG